In [1]:
# Import data and obtain descriptive statistics
import pandas as pd
df = pd.read_csv('Dataset.csv')
df.describe()

,rental_count,member_count,humidity,pressure,temperature,wind_direction,wind_speed,precipitation,new_snow,snow_depth,business_day,holiday
count,1096.000000,1.096000e+03,1096.000000,1096.000000,1096.000000,1096.000000,1096.000000,1096.000000,1096.000000,1096.000000,1096.000000,1096.000000
mean,30083.413321,1.487490e+06,66.539805,1018.278508,285.172789,200.431989,3.143667,0.125474,0.123659,0.858668,0.617701,0.023723
std,14705.852440,4.445886e+07,14.216280,7.943577,10.133459,72.805206,1.442132,0.351312,1.085763,2.949020,0.486171,0.152253
min,0.000000,9.597100e+04,25.917000,991.417000,259.020000,22.708000,0.708000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,18102.500000,1.249308e+05,56.917000,1013.083000,277.550500,148.520750,2.125000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,31238.000000,1.352705e+05,66.687500,1017.937500,285.957000,211.479000,2.875000,0.000000,0.000000,0.000000,1.000000,0.000000
75%,39641.750000,1.640488e+05,76.958000,1022.833000,294.335250,257.156500,3.833000,0.040000,0.000000,0.000000,1.000000,0.000000
max,69758.000000,1.471994e+09,100.000000,1049.458000,303.675000,341.792000,9.917000,4.970000,27.300000,22.000000,1.000000,1.000000

In [2]:
# Box plot for rental demand distribution across the year
import plotly.plotly as py
import plotly.graph_objs as go
import plotly
import calendar
data = []
for i in range(12):
    data.append(go.Box(y=df[pd.to_datetime(df['Date']).dt.month == i+1]['rental_count'], 
                       name=calendar.month_name[i+1], 
                       showlegend=False ) )
layout = go.Layout(
    title='Rental demand distribution',
    xaxis=dict(
        title='Month',
        titlefont=dict(
            size=18,
        )
    ),
    yaxis=dict(
        title='Daily rental count',
        titlefont=dict(
            size=18,
        )
    )
)
fig = go.Figure(data=data, layout=layout)
py.iplot(fig, filename='rental_demand_distribution')

/Users/Carlos/anaconda3/envs/data/lib/python3.6/site-packages/IPython/core/display.py:689: UserWarning:

Consider using IPython.display.IFrame instead

In [3]:
# Box plot for temperature distribution across the year
import plotly.plotly as py
import plotly.graph_objs as go
import plotly
import calendar
data = []
for i in range(12):
    data.append(go.Box(y=df[pd.to_datetime(df['Date']).dt.month == i+1]['temperature'], 
                       name=calendar.month_name[i+1], 
                       showlegend=False ) )

layout = go.Layout(
    title='Temperature distribution',
    xaxis=dict(
        title='Month',
        titlefont=dict(
            size=18,
        )
    ),
    yaxis=dict(
        title='Temperature (F)',
        titlefont=dict(
            size=18,
        )
    )
)
fig = go.Figure(data=data, layout=layout)
py.iplot(fig, filename='temperature_distribution')